version: '3.7'

volumes:
  redis_data: {}
  mongo_data: {}

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: gaming
    volumes:
      - mongo_data:/data/db

  # Redis
  redis:
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data